"""enhanced_typing_analytics

Revision ID: 952119df276a
Revises: 0a8ee55581c8
Create Date: 2025-07-12 16:17:35.323884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952119df276a'
down_revision: Union[str, Sequence[str], None] = '0a8ee55581c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_typing_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avg_wpm', sa.Float(), nullable=True),
    sa.Column('avg_accuracy', sa.Float(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('slow_characters', sa.Text(), nullable=True),
    sa.Column('error_prone_characters', sa.Text(), nullable=True),
    sa.Column('difficult_bigrams', sa.Text(), nullable=True),
    sa.Column('common_errors', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_typing_profiles_id'), 'user_typing_profiles', ['id'], unique=False)
    op.create_table('typing_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('char', sa.String(), nullable=False),
    sa.Column('avg_dwell_time', sa.Float(), nullable=False),
    sa.Column('dwell_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('prev_char', sa.String(), nullable=True),
    sa.Column('flight_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_typing_analytics_id'), 'typing_analytics', ['id'], unique=False)
    op.add_column('keystroke_events', sa.Column('target_char', sa.String(), nullable=True))
    op.add_column('keystroke_events', sa.Column('position_in_text', sa.Integer(), nullable=True))
    op.add_column('keystroke_events', sa.Column('is_correction', sa.String(), nullable=True))
    op.add_column('keystroke_events', sa.Column('is_error', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('accuracy_percentage', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('error_count', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('correction_count', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('words_per_minute', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('characters_per_minute', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'characters_per_minute')
    op.drop_column('sessions', 'words_per_minute')
    op.drop_column('sessions', 'correction_count')
    op.drop_column('sessions', 'error_count')
    op.drop_column('sessions', 'accuracy_percentage')
    op.drop_column('keystroke_events', 'is_error')
    op.drop_column('keystroke_events', 'is_correction')
    op.drop_column('keystroke_events', 'position_in_text')
    op.drop_column('keystroke_events', 'target_char')
    op.drop_index(op.f('ix_typing_analytics_id'), table_name='typing_analytics')
    op.drop_table('typing_analytics')
    op.drop_index(op.f('ix_user_typing_profiles_id'), table_name='user_typing_profiles')
    op.drop_table('user_typing_profiles')
    # ### end Alembic commands ###
