"""Add target_text and user_input to sessions

Revision ID: d4d766303054
Revises: 7c0920bc02d3
Create Date: 2025-06-26 13:29:27.310162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d766303054'
down_revision: Union[str, Sequence[str], None] = '7c0920bc02d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('sessions', sa.Column('target_text', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('user_input', sa.Text(), nullable=True))
    
    # Update existing rows with default values
    op.execute("UPDATE sessions SET target_text = '' WHERE target_text IS NULL")
    op.execute("UPDATE sessions SET user_input = '' WHERE user_input IS NULL")
    
    # Now make the columns NOT NULL
    op.alter_column('sessions', 'target_text', nullable=False)
    op.alter_column('sessions', 'user_input', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'user_input')
    op.drop_column('sessions', 'target_text')
    # ### end Alembic commands ###
